Masai.web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;


namespace Masai.web.Controllers;

public class HomeController : Controller
{

    public IActionResult Index()
    {
        return View();
    }


}

Masai.web/ViewComponents/SiteFooterViewComponent.cs
namespace Masai.web.ViewComponents;
using Microsoft.AspNetCore.Mvc;

public class SiteFooterViewComponent: ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View("SiteFooter");
    }
}

Masai.web/ViewComponents/SiteHeader2ViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Masai.web.ViewComponents;

public class SiteHeader2ViewComponent: ViewComponent
{ 
  public IViewComponentResult Invoke()
   {
      return View("SiteHeader2");
   }
}

Masai.web/ViewComponents/SiteHeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Masai.web.ViewComponents;

public class SiteHeaderViewComponent:ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View("SiteHeader");
    }
}

Masai.web/Views/Shared/-FooterReferences.cshtml
<script src="/Site/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="/Site/js/core/popper.min.js" type="text/javascript"></script>
<script src="/Site/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="/Site/js/plugins/bootstrap-switch.js"></script>
<script src="/Site/js/plugins/nouislider.min.js" type="text/javascript"></script>
<script src="/Site/js/plugins/bootstrap-datepicker.js" type="text/javascript"></script>
<script src="/Site/js/plugins/jquery.sharrre.js" type="text/javascript"></script>
<script src="/Site/js/now-ui-kit.js" type="text/javascript"></script>
<script src="/Site/js/plugins/countdown.min.js" type="text/javascript"></script>
<script src="/Site/js/plugins/owl.carousel.min.js" type="text/javascript"></script>
<script src="/Site/js/plugins/jquery.easing.1.3.min.js" type="text/javascript"></script>
    
<script src="/Site/js/nouislider.min.js"></script>
<!-- custom Js -->
   
<script src="/Site/js/main.js" type="text/javascript"></script>

<!--    JS Files   -->

Masai.web/Views/Shared/Components/SiteFooter/SiteFooter.cshtml
<footer class="main-footer default">
            <div class="back-to-top ">
                <a href="#">
                    <span class="icon"><i class="fa fa-chevron-up"></i></span> <span>
                        بازگشت بالا
                    </span>
                </a>
            </div>
            <div class=" servicesbg">
                <div class="footer-services container  space-10">
                    <div class="row">
                        <div class="service-item col-2 contact-box text-center">
                            <img src="/Site/img/ico/png-4.png" class="width-40" />
                            <span class="title-1 light-black">ضمانت اصل بودن</span>
                        </div>
                        <div class="service-item col-2 contact-box text-center">
                            <img src="/Site/img/ico/png-1.png" class="width-40" />
                            <span class="title-1 light-black">پرداخت در محل</span>
                        </div>
                        <div class="service-item col-2 contact-box text-center">
                            <img src="/Site/img/ico/png-2.png" class="width-40" />
                            <span class="title-1 light-black">ارسال سریع</span>
                        </div>
                        <div class="service-item col-2 contact-box text-center">
                            <img src="/Site/img/ico/png-5.png" class="width-40" />
                            <span class="title-1 light-black">فرصت 7 روزه استرداد</span>
                        </div>
                        <div class="service-item col-2 contact-box text-center">
                            <img src="/Site/img/ico/png-3.png" class="width-40" />
                            <span class="title-1 light-black">پشتیبانی تلفنی</span>
                        </div>
                        <div class="service-item col-2 contact-box text-center">
                            <img src="/Site/img/ico/png-7.png" class="width-40" />
                            <span class="title-1 light-black">هدیه نقدی</span>
                        </div>
                       
                    </div>

                </div>
            </div>
            <div class="container-fluid space-30 bg-map">

                <div class="footer-widgets container">
                    <div class="row">
                        <div class="col-12 col-md-6 col-lg-3">
                            <div class="widget-menu widget card">
                                <div class="card-header">
                                    <h3 class="card-title">درباره ما</h3>
                                </div>
                                <p class="about_footer">
                                    قالب مَسای یک پکیج کامل ایرانی با هدف بی نهایت قالب HTML و WordPress و به روز رسانی همیشگی است، که تمام ویژگی های لازم طراحی سایت را در نظر میگیرد
                                </p>
                            </div>
                        </div>
                        <div class="col-12 col-md-6 col-lg-3">
                            <div class="widget-menu widget card">
                                <div class="card-header">
                                    <h3 class="card-title">خدمات مشتریان</h3>
                                </div>
                                <ul class="footer-menu">
                                    <li>
                                        <a href="#">ارسال فوری</a>
                                    </li>
                                    <li>
                                        <a href="#">پشتیبانی سریع</a>
                                    </li>
                                    <li>
                                        <a href="#">بازگشت وجه</a>
                                    </li>
                                    <li>
                                        <a href="#">بسته بندی کالا</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-12 col-md-6 col-lg-3">
                            <div class="widget-menu widget card">
                                <div class="card-header">
                                    <h3 class="card-title">با مَسای شاپ</h3>
                                </div>
                                <ul class="footer-menu">

                                    <li>
                                        <a href="#">تامین کالا همکار</a>
                                    </li>
                                    <li>
                                        <a href="#">تخفیف سازمانی</a>
                                    </li>
                                    <li>
                                        <a href="#">تماس با ما</a>
                                    </li>
                                    <li>
                                        <a href="#">درباره ما</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-12 col-md-6 col-lg-3">
                            <div class="widget-menu widget card">
                                <div class="card-header">
                                    <h3 class="card-title">مجوزات</h3>
                                </div>
                                <div class="License_img">
                                    <a href="#" target="_blank"><img src="/Site/img/License_2.png" alt=""></a>
                                    <a href="#" target="_blank"><img src="/Site/img/License_1.png" alt=""></a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>

            <div class="copyright">
                <div class="container">
                    <p>
                        این قالب به وسیله گروه برنامه نویسی گرزک پشتیبانی میشود.
                    </p>
                </div>
            </div>
        </footer>

Masai.web/Views/Shared/_Header2References.cshtml
<div class="top-section fullscreen-container">
    <img src="/Site/img/banner_img/bg_top.jpg" class="h-100">
</div>

Masai.web/Views/Shared/_HeaderReferences.cshtml
<meta name="description" content="مَسای شاپ ">
<meta name="author" content="Mirazimi">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />


<!-- CSS Files -->
<link href="/Site/fonts/font-awesome/css/fontawesome.min.css" rel="stylesheet" />
<link href="/Site/fonts/font-awesome/css/solid.css" rel="stylesheet" />
<link href="/Site/css/bootstrap.min.css" rel="stylesheet" />
<link href="/Site/css/main_ui.css" rel="stylesheet" />
<link href="/Site/css/icon.css" rel="stylesheet" />
<link href="/Site/css/plugins/owl.carousel.css" rel="stylesheet" />
<link href="/Site/css/plugins/owl.theme.default.min.css" rel="stylesheet" />
<link href="/Site/css/nouislider.min.css" rel="stylesheet" /><link href="/Site/css/main.css" rel="stylesheet" />
<link href="/Site/css/style.css" rel="stylesheet" />

Masai.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="/Site/img/favicon.png">
    <link rel="icon" type="image/png" href="/Site/img/favicon.png">
    <title>مَسای شاپ </title>
    <partial name="_HeaderReferences"/>
    </head>

<body class="index-page sidebar-collapse">
   <partial name="_Header2References"/>
@await Component.InvokeAsync("SiteHeader")
<div class="wrapper default ">

    @await Component.InvokeAsync("SiteHeader2")
    @RenderBody()  
        @await Component.InvokeAsync("SiteFooter")
    </div>
  
    <partial name="-FooterReferences"/>
   
</body>


</html>